name: Documentation

on:
  push:
    branches: [main, master]

jobs:
  make-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: select python version
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install ".[docs]"

      - name: Build the documentation
        run: |
          jupyter-book build docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "docs/_build/html"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
